/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.MercadoriaVO;
import servicos.MercadoriaServicos;
import servicos.ServicosFactory;

/**
 *
 * @author Douglas, Josefa
 * @since 05/05/2018
 */
public class GUIManutencaoMercadoria extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Codigo", "Nome", "Fabricante", "Origem", "Preço", "Quantidade"});

    /**
     * Creates new form GUIManutencaoMercadoria
     */
    public GUIManutencaoMercadoria() {
        initComponents();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jtPesqManu = new javax.swing.JTextField();
        jCombofiltroMan = new javax.swing.JComboBox<>();
        jlPesquisa = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableMercadoria = new javax.swing.JTable();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jbBuscar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jbConfirmarAlteracao = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jtNome = new javax.swing.JTextField();
        jtFabricante = new javax.swing.JTextField();
        jtOrigem = new javax.swing.JTextField();
        jtQuantidade = new javax.swing.JTextField();
        jtPreco = new javax.swing.JTextField();
        jtCodigo = new javax.swing.JTextField();
        jlCodigo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jlOrigem = new javax.swing.JLabel();
        jlPreco = new javax.swing.JLabel();
        jlQuantidade = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Manutenção Mercadoria");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtPesqManu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPesqManuKeyReleased(evt);
            }
        });

        jCombofiltroMan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "código", "nome", "fabricante", "origem", "preço", "quantidade" }));
        jCombofiltroMan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCombofiltroManItemStateChanged(evt);
            }
        });

        jlPesquisa.setText("Pesquisa");

        jLayeredPane1.setLayer(jtPesqManu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jCombofiltroMan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jlPesquisa, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jlPesquisa)
                .addGap(18, 18, 18)
                .addComponent(jtPesqManu, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jCombofiltroMan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPesqManu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCombofiltroMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPesquisa))
                .addGap(19, 19, 19))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtableMercadoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Frabricante", "Origem", "Preço", "Quantidade"
            }
        ));
        jtableMercadoria.getTableHeader().setReorderingAllowed(false);
        jtableMercadoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMercadoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableMercadoria);

        jLayeredPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jbConfirmarAlteracao.setText("Confirmar Alteração");
        jbConfirmarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarAlteracaoActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jbBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbDeletar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbConfirmarAlteracao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jbAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbConfirmarAlteracao)
                .addGap(25, 25, 25))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jbLimpar)
                    .addComponent(jbConfirmarAlteracao)
                    .addComponent(jbDeletar)
                    .addComponent(jbAlterar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtCodigo.setEnabled(false);

        jlCodigo.setText("Código");
        jlCodigo.setEnabled(false);

        jlNome.setText("Nome");

        jLabel1.setText("Fabricante");

        jlOrigem.setText("Origem");

        jlPreco.setText("Preço");

        jlQuantidade.setText("Quantidade");

        jLayeredPane4.setLayer(jtNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtFabricante, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtOrigem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jtCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlNome, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlOrigem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlPreco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jlQuantidade, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtFabricante))
                .addGap(57, 57, 57)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPreco)
                    .addComponent(jlOrigem)
                    .addComponent(jlQuantidade))
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodigo)
                    .addComponent(jtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOrigem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNome)
                    .addComponent(jtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPreco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jlQuantidade))
                    .addComponent(jtFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane4)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencherTabela() {
        try {
            ArrayList<MercadoriaVO> mercadoria = new ArrayList<>();
            MercadoriaServicos ms = ServicosFactory.getMercadoriaServicos();
            mercadoria = ms.buscarMercadoria();

            limparTabela();

            for (int i = 0; i < mercadoria.size(); i++) {
                dtm.addRow(new String[]{
                    String.valueOf(mercadoria.get(i).getIdMercadoria()),
                    mercadoria.get(i).getNome(),
                    mercadoria.get(i).getFabricante(),
                    mercadoria.get(i).getOrigem(),
                    String.valueOf(mercadoria.get(i).getPreco()),
                    String.valueOf(mercadoria.get(i).getQuantidade()),});

            }//fecha for

            jtableMercadoria.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro!" + e.getMessage());
        }//fecha catch
    }//fecha preencherTabela

    private void limparTabela() {
        dtm.setNumRows(0);
    }//fecha limparTabela

    private void deletar() {
        try {
            int linha = jtableMercadoria.getSelectedRow();

            if (linha == 1) {
                JOptionPane.showMessageDialog(this, "Selecione uma linha!");
            } else {

                String id = jtableMercadoria.getValueAt(linha, 0).toString();
                MercadoriaServicos ms = ServicosFactory.getMercadoriaServicos();
                ms.deletarMercadoria(Long.parseLong(id));

                JOptionPane.showMessageDialog(this,
                        "Mercadoria excluído com Sucesso!");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao deletar" + e.getMessage());

        }
    }//fecha deletar

    private void filtrar() {
        try {
            if (jtPesqManu.getText().isEmpty()) {
                preencherTabela();
            } else {
                String filtro = jCombofiltroMan.getSelectedItem().toString();
                String pesq = jtPesqManu.getText();

                String query = "";
                if (filtro.equalsIgnoreCase("Código")) {
                    query = "where idmercadoria like '%" + pesq + "%'";
                } else if (filtro.equalsIgnoreCase("Nome")) {
                    query = "where nome like '%" + pesq + "%'";
                } else if (filtro.equalsIgnoreCase("Fabricante")) {
                    query = "where fabricante like '%" + pesq + "%'";
                } else if (filtro.equalsIgnoreCase("Origem")) {
                    query = "where origem like '%" + pesq + "%'";
                } else if (filtro.equalsIgnoreCase("Preço")) {
                    query = "where preço like '%" + pesq + "%'";
                } else if (filtro.equalsIgnoreCase("Quantidade")) {
                    query = "where quantidade like '%" + pesq + "%'";
                }

                MercadoriaServicos ms = ServicosFactory.getMercadoriaServicos();
                ArrayList<MercadoriaVO> mercadoria = ms.filtrar(query);

                for (int i = 0; i < mercadoria.size(); i++) {
                    dtm.addRow(new String[]{
                        String.valueOf(mercadoria.get(i).getIdMercadoria()),
                        mercadoria.get(i).getNome(),
                        String.valueOf(mercadoria.get(i).getNome()),
                        String.valueOf(mercadoria.get(i).getFabricante()),
                        String.valueOf(mercadoria.get(i).getOrigem()),
                        String.valueOf(mercadoria.get(i).getPreco()),
                        String.valueOf(mercadoria.get(i).getQuantidade()),});

                    jtableMercadoria.setModel(dtm);
                }//fecha for
            }//fecha else

        } catch (Exception e) {
            jtPesqManu.setText("");
            JOptionPane.showMessageDialog(this,
                    "Erro ao filtrar" + e.getMessage());

        }//fecha catch
    }//fecha filtrar

    private void alterar() {
        try {

            int linha = jtableMercadoria.getSelectedRow();
            if (linha == -1) {

                jtCodigo.setText((String) jtableMercadoria.getValueAt(linha, 0));
                jtNome.setText((String) jtableMercadoria.getValueAt(linha, 1));
                jtFabricante.setText((String) jtableMercadoria.getValueAt(linha, 2));
                jtOrigem.setText((String) jtableMercadoria.getValueAt(linha, 3));
                jtPreco.setText((String) jtableMercadoria.getValueAt(linha, 4));
                jtQuantidade.setText((String) jtableMercadoria.getValueAt(linha, 5));

            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Selecione uma linha!");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "erro! " + e.getMessage());
        }//fecha catch

    }//fecha método alterar

    private void confirmarAlteracao() {
        try {
            MercadoriaVO mVO = new MercadoriaVO();
            mVO.setIdMercadoria(Long.parseLong(jtCodigo.getText()));
            mVO.setNome(jtNome.getText());
            mVO.setFabricante(jtFabricante.getText());
            mVO.setOrigem(jtOrigem.getText());
            mVO.setPreco(Double.parseDouble(jtPreco.getText()));
            mVO.setQuantidade(Integer.parseInt(jtQuantidade.getText()));

            MercadoriaServicos ms = ServicosFactory.getMercadoriaServicos();

            ms.alterarMercadoria(mVO);

            JOptionPane.showMessageDialog(rootPane,
                    "Mercadoria Alterada com Sucesso!");
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "erro! " + e.getMessage());

        }//fecha catch
    }//fecha método confirmarAlteracao

    private void limparCampos() {
        jtCodigo.setText(null);
        jtNome.setText(null);
        jtFabricante.setText(null);
        jtOrigem.setText(null);
        jtPreco.setText(null);
        jtQuantidade.setText(null);

    }//fecha método limparCampos


    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        preencherTabela();
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparTabela();
        limparCampos();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        deletar();
    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbConfirmarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarAlteracaoActionPerformed
        confirmarAlteracao();
        limparTabela();
        preencherTabela();
        limparTabela();
    }//GEN-LAST:event_jbConfirmarAlteracaoActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        alterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jtPesqManuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPesqManuKeyReleased
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jtPesqManuKeyReleased

    private void jCombofiltroManItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCombofiltroManItemStateChanged
        limparTabela();
        filtrar();
    }//GEN-LAST:event_jCombofiltroManItemStateChanged

    private void jtableMercadoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMercadoriaMouseClicked
        confirmarAlteracao();
        limparTabela();
        preencherTabela();
        limparCampos();
    }//GEN-LAST:event_jtableMercadoriaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCombofiltroMan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbConfirmarAlteracao;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlOrigem;
    private javax.swing.JLabel jlPesquisa;
    private javax.swing.JLabel jlPreco;
    private javax.swing.JLabel jlQuantidade;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtFabricante;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtOrigem;
    private javax.swing.JTextField jtPesqManu;
    private javax.swing.JTextField jtPreco;
    private javax.swing.JTextField jtQuantidade;
    private javax.swing.JTable jtableMercadoria;
    // End of variables declaration//GEN-END:variables
}
