/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author Douglas, Josefa
 * @since 05/05/2018
 * @version 1.0
 */
public class MenuPrincipal extends javax.swing.JFrame implements InternalFrameListener{

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAreaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCardFamacia = new javax.swing.JMenuItem();
        jmiCardFuncionario = new javax.swing.JMenuItem();
        jmiCardMercadoria = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManFarmacia = new javax.swing.JMenuItem();
        jmiManFuncionario = new javax.swing.JMenuItem();
        jmiManMercadoria = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmCadastro.setText("Cadastro");

        jmiCardFamacia.setText("Farmacia");
        jmiCardFamacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCardFamaciaActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCardFamacia);

        jmiCardFuncionario.setText("Funcionário");
        jmiCardFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCardFuncionarioActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCardFuncionario);

        jmiCardMercadoria.setText("Mercadoria");
        jmiCardMercadoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCardMercadoriaActionPerformed(evt);
            }
        });
        jmCadastro.add(jmiCardMercadoria);

        jMenuBar1.add(jmCadastro);

        jmManutencao.setText("Manutencao");

        jmiManFarmacia.setText("Farmacia");
        jmiManFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManFarmaciaActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManFarmacia);

        jmiManFuncionario.setText("Funcionário");
        jmiManFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManFuncionarioActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManFuncionario);

        jmiManMercadoria.setText("Mercadoria");
        jmiManMercadoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManMercadoriaActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManMercadoria);

        jMenuBar1.add(jmManutencao);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jAreaTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadFarmacia(){
        GUICadFarmacia gcf = new GUICadFarmacia();
        jAreaTrabalho.add(gcf);
        gcf.setVisible(true);
        
    }//fecha método
    
    private void abrirManFarmacia(){
        GUIManutencaoFarmacia gmf = new GUIManutencaoFarmacia();
        jAreaTrabalho.add(gmf);
        gmf.setVisible(true);
        
    }//fecha método
    
    private void abrirCadMercadoria(){
           GUICadMercadoria gcm = new GUICadMercadoria();
        jAreaTrabalho.add(gcm);
        gcm.setVisible(true);
        
    }//fecha método
    
    private void abrirManMercadoira(){

        GUIManutencaoMercadoria gmm = new GUIManutencaoMercadoria();
        jAreaTrabalho.add(gmm);
        gmm.setVisible(true);
    }//fecha método
    
    
    private void abrirCadFuncionario(){
        GUICadFuncionario gcfu = new GUICadFuncionario();
        jAreaTrabalho.add(gcfu);
        gcfu.setVisible(true);
        
        
    }//fecha método
    
    private void abrirManFuncionario(){
        
        GUIManutencaoFuncionario gmfu = new GUIManutencaoFuncionario();
        jAreaTrabalho.add(gmfu);
        gmfu.setVisible(true);
    }//fecha método
    
    
    
    private void jmiCardFamaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCardFamaciaActionPerformed
        abrirCadFarmacia();
        
    }//GEN-LAST:event_jmiCardFamaciaActionPerformed

    private void jmiManFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManFarmaciaActionPerformed
        abrirManFarmacia();
    }//GEN-LAST:event_jmiManFarmaciaActionPerformed

    
    
    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
       System.exit(EXIT_ON_CLOSE);
    }//GEN-LAST:event_jmSairMouseClicked

    private void jmiCardFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCardFuncionarioActionPerformed
        abrirCadFuncionario();
    }//GEN-LAST:event_jmiCardFuncionarioActionPerformed

    private void jmiManFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManFuncionarioActionPerformed
        abrirManFuncionario();
    }//GEN-LAST:event_jmiManFuncionarioActionPerformed

    private void jmiCardMercadoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCardMercadoriaActionPerformed
       abrirCadMercadoria();
    }//GEN-LAST:event_jmiCardMercadoriaActionPerformed

    private void jmiManMercadoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManMercadoriaActionPerformed
        abrirManMercadoira();
    }//GEN-LAST:event_jmiManMercadoriaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jAreaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuItem jmiCardFamacia;
    private javax.swing.JMenuItem jmiCardFuncionario;
    private javax.swing.JMenuItem jmiCardMercadoria;
    private javax.swing.JMenuItem jmiManFarmacia;
    private javax.swing.JMenuItem jmiManFuncionario;
    private javax.swing.JMenuItem jmiManMercadoria;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
        
    }
}
